const actionsTypes = {
  REQUESTED_BOOKS_LIST: 'REQUESTED_BOOKS_LIST',
  REQUESTED_BOOKS_LIST_ASYNC: 'REQUESTED_BOOKS_LIST_ASYNC',
  REQUESTED_BOOKS_LIST_SUCCESS: 'REQUESTED_BOOKS_LIST_SUCCESS',
  REQUESTED_BOOKS_LIST_ERROR: 'REQUESTED_BOOKS_LIST_ERROR',

  SELECTED_BOOK: 'SELECTED_BOOK',
  CLOSED_POPUP: 'CLOSED_POPUP',
  ADDED_BOOKS_TO_CART: 'ADDED_BOOKS_TO_CART',
  OPENED_CART: 'OPENED_CART',
};

export default actionsTypes;
